[package]
name = "evtx-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
evtx = "0.8.4"
serde_json = "1.0"
serde = { version = "1.0.216", features = ["derive"] }
sanitize-filename = "0.6.0"
infer = "0.19.0"